### ISSUE TITLE
Testing returns all cases matching with batch size one

### ISSUE THREAD

**Issue by Sumes** [fangpin/siamese-network#3]
In all the case we are taking L1 distance of siamese fc outputs which leads to negative values. When taking sigmoid on this it always gives 0. eventually leading all values predicted correctly

**Comment by fangpin** [comment]
@Sumes 
> In all the case we are taking L1 distance of siamese fc outputs which leads to negative values. When taking sigmoid on this it always gives 0. eventually leading all values predicted correctly

What do you mean? There is no negative value since I use absolute L1 distance. See model.py
https://github.com/fangpin/siamese-pytorch/blob/cef7cec2e7928ad4002e4813597a98c02fd7201d/model.py#L35

**Comment by Sumes** [comment]
By getting all predictions as 0 means that, even dissimilar images are also
getting matched as same
