### ISSUE TITLE
Not able to reach more than 20% precision

### ISSUE THREAD

**Issue by Ameyapores** [fangpin/siamese-network#4]
Hey,
Somehow, I am unable to achieve a precision of more than 20% with the same exact code. Could you have a look?
https://github.com/Ameyapores/one_shot_learning/blob/master/notebook.ipynb

**Comment by fangpin** [comment]
There is a lack of reorganizing your training and testing folder in your code. We should keep that both of the two folders are consisting of training or testing classes (character) instead of alphabet. Refer make_dataset.py for help. @Ameyapores
