### ISSUE TITLE
Is there any inference only script?

### ISSUE THREAD

**Issue by bemoregt** [fangpin/siamese-network#9]
Hi, @urbanophile @fangpin 

Is there any inference only script?

I want to enter just two image for to get similarity result.

Thanks.
Best,
@bemoregt.

**Comment by urbanophile** [comment]
Not in this repo, sorry! In any event, there is no pretrained weights either.

**Comment by fangpin** [comment]
Sorry, I can not access the server to retrieve the model weights, since I just graduated recently. As for
the inference only script, I think it's easy for you to follow the Pythorch official tutorial to train the model, save the weights, and load the weights to infer.
